<?xml version="1.0"?>
<?xml-model
        href="http://download.ros.org/schema/package_format3.xsd"
        schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>neato_ros2_rust</name>
  <version>0.0.1</version>
  <description>ROS2 interface to Neato vacuum robots using Rust</description>
  <maintainer email="loy.vanbeek@gmail.com">Loy van Beek</maintainer>
  <license>Apache License 2.0</license>

  <depend>rclrs</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>

  <export>
    <build_type>ament_cargo</build_type>
  </export>
</package>
